<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2013/03/23 02:51:26
return array(

  // sfPropelPlugin_module_libs

  // sfPropelPlugin_lib
  'sfmixer' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/addon/sfMixer.class.php',
  'sfpropel' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/addon/sfPropel.class.php',
  'sfpropelbehavior' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/addon/sfPropelBehavior.class.php',
  'sfpropeldata' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/addon/sfPropelData.class.php',
  'sfpropeldatabaseschema' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/addon/sfPropelDatabaseSchema.class.php',
  'sfpropelmanytomany' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/addon/sfPropelManyToMany.class.php',
  'sfpropelpager' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/addon/sfPropelPager.class.php',
  'sfpropelbehaviorbase' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorBase.php',
  'sfpropelbehaviori18n' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18n.php',
  'sfpropelbehaviori18ntranslation' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18nTranslation.php',
  'sfpropelbehaviorsymfony' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfony.php',
  'sfpropelbehaviorsymfonybehaviors' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfonyBehaviors.php',
  'sfpropelbehaviortimestampable' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorTimestampable.php',
  'sfpropeldatabase' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/database/sfPropelDatabase.class.php',
  'sfwebdebugpanelpropel' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/debug/sfWebDebugPanelPropel.class.php',
  'sfformfilterpropel' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/form/sfFormFilterPropel.class.php',
  'sfformpropel' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/form/sfFormPropel.class.php',
  'sfpropelformfiltergenerator' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/generator/sfPropelFormFilterGenerator.class.php',
  'sfpropelformgenerator' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/generator/sfPropelFormGenerator.class.php',
  'sfpropelgenerator' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/generator/sfPropelGenerator.class.php',
  'sfpropellogger' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/log/sfPropelLogger.class.php',
  'swift_propelspool' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/mailer/Swift_PropelSpool.class.php',
  'sfpropelroute' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/routing/sfPropelRoute.class.php',
  'sfpropelroutecollection' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/routing/sfPropelRouteCollection.class.php',
  'sfphing' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/task/sfPhing.class.php',
  'sfphinglistener' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/task/sfPhingListener.php',
  'sfpropelbasetask' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBaseTask.class.php',
  'sfpropelbuildallloadtask' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllLoadTask.class.php',
  'sfpropelbuildalltask' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllTask.class.php',
  'sfpropelbuildfilterstask' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildFiltersTask.class.php',
  'sfpropelbuildformstask' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildFormsTask.class.php',
  'sfpropelbuildmodeltask' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildModelTask.class.php',
  'sfpropelbuildschematask' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildSchemaTask.class.php',
  'sfpropelbuildsqltask' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildSqlTask.class.php',
  'sfpropelbuildtask' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildTask.class.php',
  'sfpropelconfiguredatabasetask' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelConfigureDatabaseTask.class.php',
  'sfpropeldatadumptask' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelDataDumpTask.class.php',
  'sfpropeldataloadtask' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelDataLoadTask.class.php',
  'sfpropelgenerateadmintask' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelGenerateAdminTask.class.php',
  'sfpropelgeneratemoduleforroutetask' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleForRouteTask.class.php',
  'sfpropelgeneratemoduletask' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleTask.class.php',
  'sfpropelgraphviztask' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelGraphvizTask.class.php',
  'sfpropelinsertsqltask' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelInsertSqlTask.class.php',
  'sfpropelschematoxmltask' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToXmlTask.class.php',
  'sfpropelschematoymltask' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToYmlTask.class.php',
  'sftesterpropel' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/test/sfTesterPropel.class.php',
  'sfvalidatorpropelchoice' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelChoice.class.php',
  'sfvalidatorpropelunique' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelUnique.class.php',
  'sfwidgetformpropelchoice' => '/usr/lib/php/symfony/plugins/sfPropelPlugin/lib/widget/sfWidgetFormPropelChoice.class.php',

  // project
  'basecarformfilter' => '/Users/linuxska/sfproject/repoCarMan/lib/filter/base/BaseCarFormFilter.class.php',
  'baseuserformfilter' => '/Users/linuxska/sfproject/repoCarMan/lib/filter/base/BaseUserFormFilter.class.php',
  'baseformfilterpropel' => '/Users/linuxska/sfproject/repoCarMan/lib/filter/BaseFormFilterPropel.class.php',
  'carformfilter' => '/Users/linuxska/sfproject/repoCarMan/lib/filter/CarFormFilter.class.php',
  'userformfilter' => '/Users/linuxska/sfproject/repoCarMan/lib/filter/UserFormFilter.class.php',
  'basecarform' => '/Users/linuxska/sfproject/repoCarMan/lib/form/base/BaseCarForm.class.php',
  'baseuserform' => '/Users/linuxska/sfproject/repoCarMan/lib/form/base/BaseUserForm.class.php',
  'baseform' => '/Users/linuxska/sfproject/repoCarMan/lib/form/BaseForm.class.php',
  'baseformpropel' => '/Users/linuxska/sfproject/repoCarMan/lib/form/BaseFormPropel.class.php',
  'carform' => '/Users/linuxska/sfproject/repoCarMan/lib/form/CarForm.class.php',
  'userform' => '/Users/linuxska/sfproject/repoCarMan/lib/form/UserForm.class.php',

  // project_model
  'car' => '/Users/linuxska/sfproject/repoCarMan/lib/model/Car.php',
  'carpeer' => '/Users/linuxska/sfproject/repoCarMan/lib/model/CarPeer.php',
  'cartablemap' => '/Users/linuxska/sfproject/repoCarMan/lib/model/map/CarTableMap.php',
  'usertablemap' => '/Users/linuxska/sfproject/repoCarMan/lib/model/map/UserTableMap.php',
  'basecar' => '/Users/linuxska/sfproject/repoCarMan/lib/model/om/BaseCar.php',
  'basecarpeer' => '/Users/linuxska/sfproject/repoCarMan/lib/model/om/BaseCarPeer.php',
  'baseuser' => '/Users/linuxska/sfproject/repoCarMan/lib/model/om/BaseUser.php',
  'baseuserpeer' => '/Users/linuxska/sfproject/repoCarMan/lib/model/om/BaseUserPeer.php',
  'user' => '/Users/linuxska/sfproject/repoCarMan/lib/model/User.php',
  'userpeer' => '/Users/linuxska/sfproject/repoCarMan/lib/model/UserPeer.php',

  // application
  'myuser' => '/Users/linuxska/sfproject/repoCarMan/apps/car/lib/myUser.class.php',

  // modules
);
