<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/23 02:51:26

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=CarManagement;host=localhost',
  'username' => 'root',
  'password' => '310389rima',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
