<?php
// auto-generated by sfViewConfigHandler
// date: 2013/03/24 20:04:47
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('bootstrap_responsive.min.css', '', array ());
  $response->addStylesheet('bootstrap.css', '', array ());
  $response->addStylesheet('layout.css', '', array ());
  $response->addJavascript('bootstrap.js', '', array ());
  $response->addJavascript('jquery/jquery.js', '', array ());
  $response->addJavascript('jquery/jquery_ui_1.8.21.custom.min.js', '', array ());
  $response->addJavascript('jquery/jquery_1.7.2.min.js', '', array ());


