propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  car:
    _attributes: { phpName: Car }
    id: { phpName: Id, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    user_id: { phpName: UserId, type: INTEGER, size: '11', required: true, foreignTable: user, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    brand: { phpName: Brand, type: VARCHAR, size: '60', required: false }
    model: { phpName: Model, type: VARCHAR, size: '60', required: false }
    color: { phpName: Color, type: VARCHAR, size: '60', required: false }
    status: { phpName: Status, type: CHAR, required: false }
    mileage: { phpName: Mileage, type: INTEGER, size: '11', required: false }
    created_at: { phpName: CreatedAt, type: TIMESTAMP, required: false }
    updated_at: { phpName: UpdatedAt, type: TIMESTAMP, required: false }
    _indexes: { car_FI_1: [user_id] }
  user:
    _attributes: { phpName: User }
    id: { phpName: Id, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    first_name: { phpName: FirstName, type: VARCHAR, size: '45', required: true }
    last_name: { phpName: LastName, type: VARCHAR, size: '45', required: true }
    created_at: { phpName: CreatedAt, type: TIMESTAMP, required: false }
    updated_at: { phpName: UpdatedAt, type: TIMESTAMP, required: false }
